name: Create Artifact

on: push

env:
  NAME: python-artifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ env.NAME }}
          path: ./app