name: Create Artifact

on: push

env:
  NAME: python-artifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.NAME }}
          path: ./app