name: DeliverToDocker

on:
  push:
    branches:
      - master

jobs:
  deliver:

    runs-on: ubuntu-latest

    env:
      APP_NAME: python-docker-project

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Push to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.DOCKER_ID }}/${{ env.APP_NAME }}
        tags: 0.0.3
        registry: docker.io
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASS }}
