name: Deliver To Docker Registry

on:
  push:
    branches:
      - master

jobs:
  deliver:

    runs-on: ubuntu-latest

    env:
      APP_NAME: python-docker-project

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Push to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.DOCKER_ID }}/${{ env.APP_NAME }}
        tag: 0.0.3
        registry: docker.io
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASS }}
#    - name: Login to DockerHub
#      uses: docker/login-action@v1.10.0
#      with:
#          username: ${{ secrets.DOCKER_ID }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#    - name: Build the Docker image
#      run: docker build -t ${{ secrets.DOCKER_ID }}/${{ env.APP_NAME }}:latest .
#    - name: Push the Docker image
#      run: docker push ${{ secrets.DOCKER_ID }}/${{ env.APP_NAME }}:latest